# Site settings
title: Testing Things
email: storm@hackthatapi.com
description: >
    Learning how to blog with Jekyll.
baseurl: ""
url: "http://stormseeker.me"
markdown: redcarpet
highlighter: pygments
