# Site settings
title: Testing Things
email: storm@hackthatapi.com
description: > # this means to ignore newlines until "baseurl:"
Site where I do stuff with things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
